/* jni_slots.h -- slot indices of JNINativeInterface / JNIInvokeInterface.
 * Generated from the JNI specification's function table order (identical on
 * Android). The game calls through these tables by offset, so the order is
 * the contract; names are only used to fill slots. */
#ifndef BK_JNI_SLOTS_H
#define BK_JNI_SLOTS_H

enum {
  JNI_reserved0 = 0,
  JNI_reserved1 = 1,
  JNI_reserved2 = 2,
  JNI_reserved3 = 3,
  JNI_GetVersion = 4,
  JNI_DefineClass = 5,
  JNI_FindClass = 6,
  JNI_FromReflectedMethod = 7,
  JNI_FromReflectedField = 8,
  JNI_ToReflectedMethod = 9,
  JNI_GetSuperclass = 10,
  JNI_IsAssignableFrom = 11,
  JNI_ToReflectedField = 12,
  JNI_Throw = 13,
  JNI_ThrowNew = 14,
  JNI_ExceptionOccurred = 15,
  JNI_ExceptionDescribe = 16,
  JNI_ExceptionClear = 17,
  JNI_FatalError = 18,
  JNI_PushLocalFrame = 19,
  JNI_PopLocalFrame = 20,
  JNI_NewGlobalRef = 21,
  JNI_DeleteGlobalRef = 22,
  JNI_DeleteLocalRef = 23,
  JNI_IsSameObject = 24,
  JNI_NewLocalRef = 25,
  JNI_EnsureLocalCapacity = 26,
  JNI_AllocObject = 27,
  JNI_NewObject = 28,
  JNI_NewObjectV = 29,
  JNI_NewObjectA = 30,
  JNI_GetObjectClass = 31,
  JNI_IsInstanceOf = 32,
  JNI_GetMethodID = 33,
  JNI_CallObjectMethod = 34,
  JNI_CallObjectMethodV = 35,
  JNI_CallObjectMethodA = 36,
  JNI_CallBooleanMethod = 37,
  JNI_CallBooleanMethodV = 38,
  JNI_CallBooleanMethodA = 39,
  JNI_CallByteMethod = 40,
  JNI_CallByteMethodV = 41,
  JNI_CallByteMethodA = 42,
  JNI_CallCharMethod = 43,
  JNI_CallCharMethodV = 44,
  JNI_CallCharMethodA = 45,
  JNI_CallShortMethod = 46,
  JNI_CallShortMethodV = 47,
  JNI_CallShortMethodA = 48,
  JNI_CallIntMethod = 49,
  JNI_CallIntMethodV = 50,
  JNI_CallIntMethodA = 51,
  JNI_CallLongMethod = 52,
  JNI_CallLongMethodV = 53,
  JNI_CallLongMethodA = 54,
  JNI_CallFloatMethod = 55,
  JNI_CallFloatMethodV = 56,
  JNI_CallFloatMethodA = 57,
  JNI_CallDoubleMethod = 58,
  JNI_CallDoubleMethodV = 59,
  JNI_CallDoubleMethodA = 60,
  JNI_CallVoidMethod = 61,
  JNI_CallVoidMethodV = 62,
  JNI_CallVoidMethodA = 63,
  JNI_CallNonvirtualObjectMethod = 64,
  JNI_CallNonvirtualObjectMethodV = 65,
  JNI_CallNonvirtualObjectMethodA = 66,
  JNI_CallNonvirtualBooleanMethod = 67,
  JNI_CallNonvirtualBooleanMethodV = 68,
  JNI_CallNonvirtualBooleanMethodA = 69,
  JNI_CallNonvirtualByteMethod = 70,
  JNI_CallNonvirtualByteMethodV = 71,
  JNI_CallNonvirtualByteMethodA = 72,
  JNI_CallNonvirtualCharMethod = 73,
  JNI_CallNonvirtualCharMethodV = 74,
  JNI_CallNonvirtualCharMethodA = 75,
  JNI_CallNonvirtualShortMethod = 76,
  JNI_CallNonvirtualShortMethodV = 77,
  JNI_CallNonvirtualShortMethodA = 78,
  JNI_CallNonvirtualIntMethod = 79,
  JNI_CallNonvirtualIntMethodV = 80,
  JNI_CallNonvirtualIntMethodA = 81,
  JNI_CallNonvirtualLongMethod = 82,
  JNI_CallNonvirtualLongMethodV = 83,
  JNI_CallNonvirtualLongMethodA = 84,
  JNI_CallNonvirtualFloatMethod = 85,
  JNI_CallNonvirtualFloatMethodV = 86,
  JNI_CallNonvirtualFloatMethodA = 87,
  JNI_CallNonvirtualDoubleMethod = 88,
  JNI_CallNonvirtualDoubleMethodV = 89,
  JNI_CallNonvirtualDoubleMethodA = 90,
  JNI_CallNonvirtualVoidMethod = 91,
  JNI_CallNonvirtualVoidMethodV = 92,
  JNI_CallNonvirtualVoidMethodA = 93,
  JNI_GetFieldID = 94,
  JNI_GetObjectField = 95,
  JNI_GetBooleanField = 96,
  JNI_GetByteField = 97,
  JNI_GetCharField = 98,
  JNI_GetShortField = 99,
  JNI_GetIntField = 100,
  JNI_GetLongField = 101,
  JNI_GetFloatField = 102,
  JNI_GetDoubleField = 103,
  JNI_SetObjectField = 104,
  JNI_SetBooleanField = 105,
  JNI_SetByteField = 106,
  JNI_SetCharField = 107,
  JNI_SetShortField = 108,
  JNI_SetIntField = 109,
  JNI_SetLongField = 110,
  JNI_SetFloatField = 111,
  JNI_SetDoubleField = 112,
  JNI_GetStaticMethodID = 113,
  JNI_CallStaticObjectMethod = 114,
  JNI_CallStaticObjectMethodV = 115,
  JNI_CallStaticObjectMethodA = 116,
  JNI_CallStaticBooleanMethod = 117,
  JNI_CallStaticBooleanMethodV = 118,
  JNI_CallStaticBooleanMethodA = 119,
  JNI_CallStaticByteMethod = 120,
  JNI_CallStaticByteMethodV = 121,
  JNI_CallStaticByteMethodA = 122,
  JNI_CallStaticCharMethod = 123,
  JNI_CallStaticCharMethodV = 124,
  JNI_CallStaticCharMethodA = 125,
  JNI_CallStaticShortMethod = 126,
  JNI_CallStaticShortMethodV = 127,
  JNI_CallStaticShortMethodA = 128,
  JNI_CallStaticIntMethod = 129,
  JNI_CallStaticIntMethodV = 130,
  JNI_CallStaticIntMethodA = 131,
  JNI_CallStaticLongMethod = 132,
  JNI_CallStaticLongMethodV = 133,
  JNI_CallStaticLongMethodA = 134,
  JNI_CallStaticFloatMethod = 135,
  JNI_CallStaticFloatMethodV = 136,
  JNI_CallStaticFloatMethodA = 137,
  JNI_CallStaticDoubleMethod = 138,
  JNI_CallStaticDoubleMethodV = 139,
  JNI_CallStaticDoubleMethodA = 140,
  JNI_CallStaticVoidMethod = 141,
  JNI_CallStaticVoidMethodV = 142,
  JNI_CallStaticVoidMethodA = 143,
  JNI_GetStaticFieldID = 144,
  JNI_GetStaticObjectField = 145,
  JNI_GetStaticBooleanField = 146,
  JNI_GetStaticByteField = 147,
  JNI_GetStaticCharField = 148,
  JNI_GetStaticShortField = 149,
  JNI_GetStaticIntField = 150,
  JNI_GetStaticLongField = 151,
  JNI_GetStaticFloatField = 152,
  JNI_GetStaticDoubleField = 153,
  JNI_SetStaticObjectField = 154,
  JNI_SetStaticBooleanField = 155,
  JNI_SetStaticByteField = 156,
  JNI_SetStaticCharField = 157,
  JNI_SetStaticShortField = 158,
  JNI_SetStaticIntField = 159,
  JNI_SetStaticLongField = 160,
  JNI_SetStaticFloatField = 161,
  JNI_SetStaticDoubleField = 162,
  JNI_NewString = 163,
  JNI_GetStringLength = 164,
  JNI_GetStringChars = 165,
  JNI_ReleaseStringChars = 166,
  JNI_NewStringUTF = 167,
  JNI_GetStringUTFLength = 168,
  JNI_GetStringUTFChars = 169,
  JNI_ReleaseStringUTFChars = 170,
  JNI_GetArrayLength = 171,
  JNI_NewObjectArray = 172,
  JNI_GetObjectArrayElement = 173,
  JNI_SetObjectArrayElement = 174,
  JNI_NewBooleanArray = 175,
  JNI_NewByteArray = 176,
  JNI_NewCharArray = 177,
  JNI_NewShortArray = 178,
  JNI_NewIntArray = 179,
  JNI_NewLongArray = 180,
  JNI_NewFloatArray = 181,
  JNI_NewDoubleArray = 182,
  JNI_GetBooleanArrayElements = 183,
  JNI_GetByteArrayElements = 184,
  JNI_GetCharArrayElements = 185,
  JNI_GetShortArrayElements = 186,
  JNI_GetIntArrayElements = 187,
  JNI_GetLongArrayElements = 188,
  JNI_GetFloatArrayElements = 189,
  JNI_GetDoubleArrayElements = 190,
  JNI_ReleaseBooleanArrayElements = 191,
  JNI_ReleaseByteArrayElements = 192,
  JNI_ReleaseCharArrayElements = 193,
  JNI_ReleaseShortArrayElements = 194,
  JNI_ReleaseIntArrayElements = 195,
  JNI_ReleaseLongArrayElements = 196,
  JNI_ReleaseFloatArrayElements = 197,
  JNI_ReleaseDoubleArrayElements = 198,
  JNI_GetBooleanArrayRegion = 199,
  JNI_GetByteArrayRegion = 200,
  JNI_GetCharArrayRegion = 201,
  JNI_GetShortArrayRegion = 202,
  JNI_GetIntArrayRegion = 203,
  JNI_GetLongArrayRegion = 204,
  JNI_GetFloatArrayRegion = 205,
  JNI_GetDoubleArrayRegion = 206,
  JNI_SetBooleanArrayRegion = 207,
  JNI_SetByteArrayRegion = 208,
  JNI_SetCharArrayRegion = 209,
  JNI_SetShortArrayRegion = 210,
  JNI_SetIntArrayRegion = 211,
  JNI_SetLongArrayRegion = 212,
  JNI_SetFloatArrayRegion = 213,
  JNI_SetDoubleArrayRegion = 214,
  JNI_RegisterNatives = 215,
  JNI_UnregisterNatives = 216,
  JNI_MonitorEnter = 217,
  JNI_MonitorExit = 218,
  JNI_GetJavaVM = 219,
  JNI_GetStringRegion = 220,
  JNI_GetStringUTFRegion = 221,
  JNI_GetPrimitiveArrayCritical = 222,
  JNI_ReleasePrimitiveArrayCritical = 223,
  JNI_GetStringCritical = 224,
  JNI_ReleaseStringCritical = 225,
  JNI_NewWeakGlobalRef = 226,
  JNI_DeleteWeakGlobalRef = 227,
  JNI_ExceptionCheck = 228,
  JNI_NewDirectByteBuffer = 229,
  JNI_GetDirectBufferAddress = 230,
  JNI_GetDirectBufferCapacity = 231,
  JNI_GetObjectRefType = 232,
  JNI_GetModule = 233,
  JNI_IsVirtualThread = 234,
  JNI_GetStringUTFLengthAsLong = 235,
  JNI_HasIdentity = 236,
  JNI_SLOT_COUNT = 237
};

enum {
  JVM_reserved0 = 0,
  JVM_reserved1 = 1,
  JVM_reserved2 = 2,
  JVM_DestroyJavaVM = 3,
  JVM_AttachCurrentThread = 4,
  JVM_DetachCurrentThread = 5,
  JVM_GetEnv = 6,
  JVM_AttachCurrentThreadAsDaemon = 7,
  JVM_SLOT_COUNT = 8
};

static const char *const k_jni_slot_names[JNI_SLOT_COUNT] = {
  "reserved0",
  "reserved1",
  "reserved2",
  "reserved3",
  "GetVersion",
  "DefineClass",
  "FindClass",
  "FromReflectedMethod",
  "FromReflectedField",
  "ToReflectedMethod",
  "GetSuperclass",
  "IsAssignableFrom",
  "ToReflectedField",
  "Throw",
  "ThrowNew",
  "ExceptionOccurred",
  "ExceptionDescribe",
  "ExceptionClear",
  "FatalError",
  "PushLocalFrame",
  "PopLocalFrame",
  "NewGlobalRef",
  "DeleteGlobalRef",
  "DeleteLocalRef",
  "IsSameObject",
  "NewLocalRef",
  "EnsureLocalCapacity",
  "AllocObject",
  "NewObject",
  "NewObjectV",
  "NewObjectA",
  "GetObjectClass",
  "IsInstanceOf",
  "GetMethodID",
  "CallObjectMethod",
  "CallObjectMethodV",
  "CallObjectMethodA",
  "CallBooleanMethod",
  "CallBooleanMethodV",
  "CallBooleanMethodA",
  "CallByteMethod",
  "CallByteMethodV",
  "CallByteMethodA",
  "CallCharMethod",
  "CallCharMethodV",
  "CallCharMethodA",
  "CallShortMethod",
  "CallShortMethodV",
  "CallShortMethodA",
  "CallIntMethod",
  "CallIntMethodV",
  "CallIntMethodA",
  "CallLongMethod",
  "CallLongMethodV",
  "CallLongMethodA",
  "CallFloatMethod",
  "CallFloatMethodV",
  "CallFloatMethodA",
  "CallDoubleMethod",
  "CallDoubleMethodV",
  "CallDoubleMethodA",
  "CallVoidMethod",
  "CallVoidMethodV",
  "CallVoidMethodA",
  "CallNonvirtualObjectMethod",
  "CallNonvirtualObjectMethodV",
  "CallNonvirtualObjectMethodA",
  "CallNonvirtualBooleanMethod",
  "CallNonvirtualBooleanMethodV",
  "CallNonvirtualBooleanMethodA",
  "CallNonvirtualByteMethod",
  "CallNonvirtualByteMethodV",
  "CallNonvirtualByteMethodA",
  "CallNonvirtualCharMethod",
  "CallNonvirtualCharMethodV",
  "CallNonvirtualCharMethodA",
  "CallNonvirtualShortMethod",
  "CallNonvirtualShortMethodV",
  "CallNonvirtualShortMethodA",
  "CallNonvirtualIntMethod",
  "CallNonvirtualIntMethodV",
  "CallNonvirtualIntMethodA",
  "CallNonvirtualLongMethod",
  "CallNonvirtualLongMethodV",
  "CallNonvirtualLongMethodA",
  "CallNonvirtualFloatMethod",
  "CallNonvirtualFloatMethodV",
  "CallNonvirtualFloatMethodA",
  "CallNonvirtualDoubleMethod",
  "CallNonvirtualDoubleMethodV",
  "CallNonvirtualDoubleMethodA",
  "CallNonvirtualVoidMethod",
  "CallNonvirtualVoidMethodV",
  "CallNonvirtualVoidMethodA",
  "GetFieldID",
  "GetObjectField",
  "GetBooleanField",
  "GetByteField",
  "GetCharField",
  "GetShortField",
  "GetIntField",
  "GetLongField",
  "GetFloatField",
  "GetDoubleField",
  "SetObjectField",
  "SetBooleanField",
  "SetByteField",
  "SetCharField",
  "SetShortField",
  "SetIntField",
  "SetLongField",
  "SetFloatField",
  "SetDoubleField",
  "GetStaticMethodID",
  "CallStaticObjectMethod",
  "CallStaticObjectMethodV",
  "CallStaticObjectMethodA",
  "CallStaticBooleanMethod",
  "CallStaticBooleanMethodV",
  "CallStaticBooleanMethodA",
  "CallStaticByteMethod",
  "CallStaticByteMethodV",
  "CallStaticByteMethodA",
  "CallStaticCharMethod",
  "CallStaticCharMethodV",
  "CallStaticCharMethodA",
  "CallStaticShortMethod",
  "CallStaticShortMethodV",
  "CallStaticShortMethodA",
  "CallStaticIntMethod",
  "CallStaticIntMethodV",
  "CallStaticIntMethodA",
  "CallStaticLongMethod",
  "CallStaticLongMethodV",
  "CallStaticLongMethodA",
  "CallStaticFloatMethod",
  "CallStaticFloatMethodV",
  "CallStaticFloatMethodA",
  "CallStaticDoubleMethod",
  "CallStaticDoubleMethodV",
  "CallStaticDoubleMethodA",
  "CallStaticVoidMethod",
  "CallStaticVoidMethodV",
  "CallStaticVoidMethodA",
  "GetStaticFieldID",
  "GetStaticObjectField",
  "GetStaticBooleanField",
  "GetStaticByteField",
  "GetStaticCharField",
  "GetStaticShortField",
  "GetStaticIntField",
  "GetStaticLongField",
  "GetStaticFloatField",
  "GetStaticDoubleField",
  "SetStaticObjectField",
  "SetStaticBooleanField",
  "SetStaticByteField",
  "SetStaticCharField",
  "SetStaticShortField",
  "SetStaticIntField",
  "SetStaticLongField",
  "SetStaticFloatField",
  "SetStaticDoubleField",
  "NewString",
  "GetStringLength",
  "GetStringChars",
  "ReleaseStringChars",
  "NewStringUTF",
  "GetStringUTFLength",
  "GetStringUTFChars",
  "ReleaseStringUTFChars",
  "GetArrayLength",
  "NewObjectArray",
  "GetObjectArrayElement",
  "SetObjectArrayElement",
  "NewBooleanArray",
  "NewByteArray",
  "NewCharArray",
  "NewShortArray",
  "NewIntArray",
  "NewLongArray",
  "NewFloatArray",
  "NewDoubleArray",
  "GetBooleanArrayElements",
  "GetByteArrayElements",
  "GetCharArrayElements",
  "GetShortArrayElements",
  "GetIntArrayElements",
  "GetLongArrayElements",
  "GetFloatArrayElements",
  "GetDoubleArrayElements",
  "ReleaseBooleanArrayElements",
  "ReleaseByteArrayElements",
  "ReleaseCharArrayElements",
  "ReleaseShortArrayElements",
  "ReleaseIntArrayElements",
  "ReleaseLongArrayElements",
  "ReleaseFloatArrayElements",
  "ReleaseDoubleArrayElements",
  "GetBooleanArrayRegion",
  "GetByteArrayRegion",
  "GetCharArrayRegion",
  "GetShortArrayRegion",
  "GetIntArrayRegion",
  "GetLongArrayRegion",
  "GetFloatArrayRegion",
  "GetDoubleArrayRegion",
  "SetBooleanArrayRegion",
  "SetByteArrayRegion",
  "SetCharArrayRegion",
  "SetShortArrayRegion",
  "SetIntArrayRegion",
  "SetLongArrayRegion",
  "SetFloatArrayRegion",
  "SetDoubleArrayRegion",
  "RegisterNatives",
  "UnregisterNatives",
  "MonitorEnter",
  "MonitorExit",
  "GetJavaVM",
  "GetStringRegion",
  "GetStringUTFRegion",
  "GetPrimitiveArrayCritical",
  "ReleasePrimitiveArrayCritical",
  "GetStringCritical",
  "ReleaseStringCritical",
  "NewWeakGlobalRef",
  "DeleteWeakGlobalRef",
  "ExceptionCheck",
  "NewDirectByteBuffer",
  "GetDirectBufferAddress",
  "GetDirectBufferCapacity",
  "GetObjectRefType",
  "GetModule",
  "IsVirtualThread",
  "GetStringUTFLengthAsLong",
  "HasIdentity",
};

#endif
